common.o: common.c ../src/isds.h
getreceived.o: getreceived.c ../src/isds.h common.h
getreceivedenvelope.o: getreceivedenvelope.c ../src/isds.h common.h
getsent.o: getsent.c ../src/isds.h common.h
getsignedreceived.o: getsignedreceived.c ../src/isds.h common.h
getsignedsent.o: getsignedsent.c ../src/isds.h common.h
isdsclient.o: isdsclient.c ../src/isds.h common.h
verifyreceivedhash.o: verifyreceivedhash.c ../src/isds.h common.h
